on:
  push

env:
  AWS_REGION: eu-west-1

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - name: Installing node.js
        uses: actions/setup-node@v2 # Used to install node environment - https://github.com/actions/setup-node
        with:
          node-version: '14.x' # Use the same node.js version as the one Vercel's uses (currently node14.x)
      - name: Checkout repo
        uses: actions/checkout@master
      - id: matrix
        run: |
          npx lerna list --loglevel=silent --json > packages.json
          echo "::set-output name=value::$(jq '[.[].name]' packages.json -c)"
  build:
    needs: [ setup ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{fromJson(needs.setup.outputs.matrix)}}
    steps:
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: packages/${{ matrix.value }}
          file: Dockerfile
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ matrix.value }}:${{ github.sha }}